### ISSUE TITLE
on-liner text with markdown is not working

### ISSUE THREAD

**Issue by mschwehl** [ijgnd/anki21__PFP_table#10]
Hello ijgnd

when you have a onliner in your field like test | test2
the html-view shows  test | test2 as well (no html-format)

then select all the text  test | test2 and press the shortcut for table, the errormessage will be 'select one than more line'

Als there is markdown and a delimiter "|" is provided you can render the table

note: there should be no heading as well if the checkbox heading is unset

Best wishes and thank you much

**Comment by ijgnd** [comment]
> when you have a onliner in your field like test | test2 [and] then select all the text ... and press the shortcut for table ...

Yes the solution here is far from perfect. The reason for the message you see is [here](https://github.com/ijgnd/anki__editor_add_table/blob/61ad1978100e0d3a9b7704b179a74b7809f5326b/src/addTable.py#L286). This limitation/check is inherited from the original power format pack for 2.0.

I'll try to replace all the custom code and instead rely on an external markdown library which also would fix issues like #7, #8. It's on my todo-list (see #9) but there is no timeline for this. I just updated the ankiweb description to warn about this shortcoming.

&nbsp;
> note: there should be no heading as well if the checkbox heading is unset

This sounds like an error that should not happen. But I can't reproduce it. Can you give me exact steps on how to get this bug. Thanks

**Comment by mschwehl** [comment]
here are the steps to reproduce

in a textfield type a {enter} b 
output:
```
a
b
```

inspect html: 

`a<div>b</div>`

then select all, hit the table button. A dialog showes up, checkbox 'First row is heading' is unchecked. Press ok

you will see that a is written in bold letter

using anki 2.1

best wishes

**Comment by ijgnd** [comment]
Thanks. This seems like another limitation inherited from the power format pack. I added this as a separate issue (#11). I think the fix will be once more #9.

**Comment by ijgnd** [comment]
afair I fixed this about 1.5 years ago with https://github.com/ijgnd/anki__editor_add_table/commit/cc51fdeaf17399a6fc69a193174b3eff90d1d95d
