### ISSUE TITLE
md tables always have a header

### ISSUE THREAD

**Issue by ijgnd** [ijgnd/anki21__PFP_table#11]

**Comment by aPaci95** [comment]
Would it be possible to add the option to not use header rows?

**Comment by ijgnd** [comment]
Apparently most markdown converts don't support tables without headers, see https://stackoverflow.com/questions/17536216/create-a-table-without-a-header-in-markdown and in the long run I guess I should switch to one in the long run, see https://github.com/ijgnd/anki__editor_add_table/issues/9

I just made some changes and uploaded them to github. You could try out the latest version of the file addTable.py from https://github.com/ijgnd/anki__editor_add_table/blob/master/src/addTable.py . In the config of the add-on you can add a new key named `"md: format selection text, default to head"`. For tables without a head to set the alignment it should work to write a line like `-|-` as the first line on top. The changes are not really tested so I depend on you for error reports.

**Comment by aPaci95** [comment]
Thank you very much! I'll test it ASAP and i'll report back to you!

**Comment by aPaci95** [comment]
Sorry if i reply just now but i was overwhelmed by things to do. Anyway I'm sorry but I couldn't get it to work ... maybe I'm doing something wrong...

**Comment by ijgnd** [comment]
I've uploaded the code to ankiweb weeks ago for Anki versions 2.1.45. 

I don't remember much about this thread and the changes I made in July. If you reset the user config to defaults you should see an entry `"md: format selection text, default to head"`. Set this to false and restart.

**Comment by aPaci95** [comment]
Hello, even if i set "first row is head" to false in the config, it still makes the first row as head. This only happen when i use the shortcut to create the table from cell1 | cell2 ecc. while it works fine if i create the table first through the menu.
I'm on anki 2.1.44... is there any fix? Is this intended? Am I doing something wrong?

**Comment by ijgnd** [comment]
on ankiweb it's only for .45+ 

it should work on .44 but I'm not uploading it for .44. I prefer to limit the distribution of a potentially breaking new feature that few people want.

You could download the src folder from this github repo and delete the manifest.json file in it and delete existing add-on you have. If you don't know what I mean or run into an error I can't help - then just wait until you update to anki .45+

**Comment by aPaci95** [comment]
Unfortunately it doesn't work for .44; thank you very much for your time!

**Comment by ijgnd** [comment]
after downloading the src folder have you also adjusted the setting "md: format selection text, default to head"

>  if i set "first row is head"

that's not the setting that you need to change here because `table_style__first_row_is_head_default` is not applied to md, it's `"md: format selection text, default to head"`. The naming might be better ... 

Maybe I could change it but I liked the idea to be able to control this separately - e.g. if I use md for simple stuff that don't need a header whereas I use the dialog for complicated stuff that needs a header.

**Comment by aPaci95** [comment]
The problem is that when i create the addon folder (deleting the old one, as well as the manifest file) and try to launch anki, it shows this error:

![image](https://user-images.githubusercontent.com/25055620/133438169-d0aa0653-761c-4a88-8764-9033625d07f3.png)

**Comment by ijgnd** [comment]
I forgot that the add-on has a GUI element that needs to be compiled and in the github source folder in only have the source code file. So my first suggestion was bad.

New idea. Download the compiled version for .45+ from ankiweb. Open the following adress in your browser: https://ankiweb.net/shared/download/1237621971?v=2.1&p=47  (anki internally calls this url to download add-ons).

then extract it to addons21. Make sure to delete the manifest.json file from this new folder so that Anki doesn't know that you have a version of the add table add-on. Otherwise there might be complications with auto-updating, getting the version info from ankiweb applied. I don't have all the details in my mind but there could be some and the easiest thing is to fully make this add-on indepenent from ankiweb.

**Comment by aPaci95** [comment]
It works like a charm! Thank you very much!!!
