### ISSUE TITLE
Text alignments in markdown not converting to html

### ISSUE THREAD

**Issue by madmaximux** [ijgnd/anki21__PFP_table#13]
Example markdown:
```
| presidents | age at inauguration |
|:--|--:|
| George Washington | 57 |
| John Adams | 61|
| Thomas Jefferson| 57 |
```

Resulting table:
```
<table class="table_class_one">
‹thead><tr><th>presidents</th><th>age at inauguration</th></tr></thead>
<tbody><tr><td>George Washington</td><td>57</td></tr><tr><td>John Adams</td><td>61</td></tr><tr><td-Thomas Jefferson</td><td>57</td></tr></tbody></table>
```

<img width="353" alt="image" src="https://user-images.githubusercontent.com/68623691/161864900-f85a56a9-cf7c-40a0-8c68-35e3853bc477.png">

**Comment by ijgnd** [comment]
Thanks for the report.

I didn't take into account that the alignment indicators can contain multiple dashes. The current version of the add-on only processes strings like `:-`, `:-:`, `-:`, see [here](https://github.com/ijgnd/anki__editor_add_table/blob/0a753c3c5c53e9ae25ed8bf1415347737d0cdc02/src/addTable.py#L35). 

I've added this to my todo list.

**Comment by madmaximux** [comment]
Thanks!

**Comment by madmaximux** [comment]
Could do this via regex matching. I could try to mess with it and push a PR. That is unless you wanted to try a something else. 

Edit: or a line that does some cleaning - removes  extra dashes out.

**Comment by ijgnd** [comment]
If you have pull request, I'd be happy to merge it. That would be much easier for me. Thanks. Just to be safe: Could you also state that you license your code as GPLv3+

**Comment by madmaximux** [comment]
Sure. You can add it to whatever license you already have. GPL3 is fine. 

---

Added a simple regex sub to remove the extra dashes (`s = re.sub("\\-{2,}","-",s)`), but realized that that was not the issue.

The following examples have one dash but the same issue occurs.

```
| presidents | age at inauguration |
|:-|-:|
| George Washington | test |
| John Adams | test|
| Thomas Jefferson| test |
```

```
 presidents | age at inauguration 
:-|-:
 George Washington | test 
 John Adams | test
 Thomas Jefferson| test 
```

I replaced the numbers with text in case the numbers were being forced into left alignment.

**Comment by madmaximux** [comment]
It's as if the alignment as a whole is being ignored. I can take a look at it ....

The function `get_alignment()` is working ok (esp with the edit). So will need to look downstream and see what's up 😛 .


```
>>> get_alignment(":---:")
'center'
>>> get_alignment(":---")
'left'
>>> get_alignment(":---:")
'center'
>>> get_alignment("---:")
'right'
```

**Comment by madmaximux** [comment]
Ok i figured it out. Styling was missing from `BODY_STYLING` and `HEAD_STYLING` in the default config.

Issue:

```json
    "table_style_css_V4": {
        "css1": {
            "BODY_STYLING": "",
            "HEAD_STYLING": "",
            "TABLE_STYLING": " class='table_class_one' "
        },
        "css2": {
            "BODY_STYLING": "",
            "HEAD_STYLING": "",
            "TABLE_STYLING": " class='table_class_two' ",
        },
        "unstyled": {
            "BODY_STYLING": "",
            "HEAD_STYLING": "",
            "TABLE_STYLING": ""
        }
}
```

Fix:


```json
    "table_style_css_V4": {
        "css1": {
            "BODY_STYLING": "style='{0}'",
            "HEAD_STYLING": "style='{0}'",
            "TABLE_STYLING": " class='table_class_one' "
        },
        "css2": {
            "BODY_STYLING": "style='{0}'",
            "HEAD_STYLING": "style='{0}'",
            "TABLE_STYLING": " class='table_class_two' ",
        },
        "unstyled": {
            "BODY_STYLING": "style='{0}'",
            "HEAD_STYLING": "style='{0}'",
            "TABLE_STYLING": ""
        }
}
```

`style='{0}'` is needed in the above  or else `Hstyle.format(style)` and `Bstyle.format(style)` resolves to `""`.

**Comment by ijgnd** [comment]
thanks. I'll add this to the next update, too. If you run into problems reopen this or open another issue.

I guess the best solution would be [use markdown library to convert md tables](https://github.com/ijgnd/anki__editor_add_table/issues/9).

**Comment by madmaximux** [comment]
Thanks!
