### ISSUE TITLE
gfm and backticks and vertical bars

### ISSUE THREAD

**Issue by ijgnd** [ijgnd/anki21__PFP_table#7]
The following code 

    | Name | Description |
    | ------------------------------------------------------------ | ------------- |
    | `AND`, `&&` | Logical AND |
    | `NOT`, `!` | Negates value |
    | `OR`, `||` | Logical OR |
    | `XOR` | Logical XOR |

is rendered as follows by gfm:

| Name | Description |
| ------------------------------------------------------------ | ------------- |
| `AND`, `&&` | Logical AND |
| `NOT`, `!` | Negates value |
| `OR`, `||` | Logical OR |
| `XOR` | Logical XOR |

**Comment by OrdinaryYZH** [comment]
THX for reply, I can understand gfm and other parsers don't ignore vertical bars inside backticks
but the add-ons don't parse `` to code style ,I think it is a ploblem.
and it can't turn to code after parse to table,if it can work like markdown is better
PS:if the auto-markdown add-ons support table feature, I don't use the table add-ons :)  

below is the result for the code in the add-ons:
```
| Name | Description |
| ------------------------------------------------------------ | ------------- |
| `AND`, `&&` | Logical AND |
| `NOT`, `!` | Negates value |
| `OR`, `\|\|` | Logical OR |
| `XOR` | Logical XOR |
```

![image](https://user-images.githubusercontent.com/10287222/77844071-dee8e880-71d5-11ea-9957-ffaf6b72c8f7.png)
